apiVersion: apps/v1
kind: Deployment
metadata:
  name: middletier-container
spec:
  selector:
    matchLabels:
      app: middletier-container
  replicas: 2
  template:
    metadata:
      labels:
        app: middletier-container
    spec:
      containers:
        - name: middletier-container
          image: fedex-middle-tier
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: jdbc:mysql://middletier-db:3306/middle-tier
            - name: DATABASE_USERNAME
              value: root
            - name: DATABASE_PASSWORD
              value: root
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: middletier-container
spec:
  type: NodePort
  selector:
    app: middletier-container
  ports:
    - port: 8080
      targetPort: 8080
